//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowTimeInfoAboutMetrobusLines
    {
        public string LineID { get; set; }
        public string LineName { get; set; }
        public string Times { get; set; }
        public string TimeType { get; set; }
    }
}
